### ISSUE TITLE
Javascript error with most recent versions

### ISSUE THREAD

**Issue by uroni** [discourse/discourse-canned-replies#10]
Error in combination with Discourse v1.6.9 .

TypeError: h is undefined
Url: https://forums.urbackup.org/assets/ember_jquery-c9524b48466ee05bcf3f9ddaf05405387eb17017e61e90e76628f989db37eb4e.js
Line: 5
Column: 21810

Please tell me if you need more details.

**Comment by SamSaffron** [comment]
we are going to need a repro, 1.6.9 is long unsupported ...
